## travis configuration file

language: c

sudo: false

compiler:
  - gcc

before_script:
  - autoreconf -vfi

script: 
  - ./configure || { cat config.log; false; }
  - make clean all check || { cat test/test-suite.log; false; }
  - make distcheck

## whitelist
branches:
  only:
    - master
    - next
    - coverity-scan

notifications:
  email:
    - devel@fresse.org

addons:
  apt:
    packages:
